# Generated by Django 4.2.7 on 2025-10-06 05:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('forms_count', models.IntegerField(default=0)),
                ('inputs_count', models.IntegerField(default=0)),
                ('selects_count', models.IntegerField(default=0)),
                ('links_count', models.IntegerField(default=0)),
                ('scripts_count', models.IntegerField(default=0)),
                ('raw_html', models.TextField(blank=True)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourtRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(blank=True, max_length=100)),
                ('case_number', models.CharField(blank=True, max_length=100)),
                ('party_name', models.CharField(blank=True, max_length=200)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='scraper.scrapingsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
